---
apiVersion: autoscaling/v1 
kind: HorizontalPodAutoscaler
metadata:
  name: svc
spec:
  scaleTargetRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: deploy
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 40