---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: qa
  serviceName: "mongo"
  replicas: 2
  template:
    metadata:
      labels:
        app: qa
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo:4.4
          args:
            - "--dbpath"
            - "/data/db"
          command:
            - "mongod"
            - "--bind_ip"
            - "0.0.0.0"
            - "--replSet"
            - "rs0"
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "devops"
          volumeMounts:
            - mountPath: /data/db
              name: pvc-claim
  volumeClaimTemplates:
    - metadata:
        name: pvc-claim
      spec:
        accessModes: [ ReadWriteOnce ]
        storageClassName: "stg"
        resources:
          requests:
            storage: 1Gi
            
