---
apiVersion: v1
kind: CronJob
metadata:
  name: cronjob
spec:
  schedule: '* * * * *'
  jobTemplate:
    metadata:
      name: cronjob-job
      labels:
        app: qa
    spec:
      selector:
        mattchLabels:
          labels:
            app: qa
      template:
        metadata:
          name: cronjob-pod
          labels:
            app: qa
        spec:
          containers:
            - name: jenkins
              image: jenkins/jenkins
              command:
                - sleep
                - 1d
              ports:
                - containerPort: 8080
             
      
