---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  my-replicaset-app
spec:
  minReadySeconds: 2
  replicas: 10
  selector:
    matchLabels:
      env1: dev
  template:
    metadata:
      labels:
        env1: dev
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 5000