---
apiVersion: v1
kind: Pod
metadata:
  name: k8s1
  labels:
    env1: dev
spec:
  containers:
    - name: nop
      image: batchusivaji/nopcommerce:latest
      ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Pod
metadata:
  name: k8s2
  labels:
    env1: dev
spec:
  containers:
    - name: nop
      image: batchusivaji/nopcommerce:latest
      ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Pod
metadata:
  name: k8s3
  labels:
    env1: dev
spec:
  containers:
    - name: nop
      image: batchusivaji/nopcommerce:latest
      ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Pod
metadata:
  name: k8s4
  labels:
    env1: dev
spec:
  containers:
    - name: nop
      image: batchusivaji/nopcommerce:latest
      ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Pod
metadata:
  name: k8s5
  labels:
    env1: dev
spec:
  containers:
    - name: nop
      image: batchusivaji/nopcommerce:latest
      ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Pod
metadata:
  name: k8s6
  labels:
    env1: dev
spec:
  containers:
    - name: nop
      image: batchusivaji/nopcommerce:latest
      ports:
        - containerPort: 5000
