---
apiVersion: v1
kind: ReplicationController
metadata:
  name:  my-replication-controller
spec:
  minReadySeconds: 2
  replicas: 10
  selector:
    env1: dev
  template:
    metadata:
      labels:
        env1: dev
    spec:
      containers:
        - name: nop
          image: batchusivaji/nopcommerce:latest
          ports:
            - containerPort: 5000