---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web-server
spec:
  minReadySeconds: 2
  replicas: 10
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      nodeSelector:
        app: jenkins
      tolerations:
        - key: app
          value: jenkins
          operator: "Equal"
          effect: NoSchedule              
      containers:
        - name: nginx
          image: nginx