---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs
spec:
  minReadySeconds: 2
  replicas: 15
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec: 
      tolerations:
        - effect: NoSchedule
          operator: Exists    
      containers:
        - name: nginx
          image: nginx