---
apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
  containers:
    - name: alpine
      image: alpine
      args:
        - sleep
        - 1d
      volumeMounts:
        - mountPath: /data
          name: my-volume
      env:
        - name: ENV-HOST
          valueFrom:
            fieldRef: 
              fieldPath: metadata.name
  volumes:
    - name: my-volume
      emptyDir: {}
       
