---
apiVersion: v1
kind: Pod
metadata:
  name: security
spec:
  containers:
    - name: nginx
      image: nginx
      command:
        - sleep
        - 1d
      envFrom:
        - configMapRef:
            name: configmap-info
        - secretRef:
            name: secret-info