---
apiVersion: v1
kind: Pod
metadata:
  name: secret
spec:
  containers:
    - name: redis
      image: redis:latest
      command:
        - sleep
        - 1d
      volumeMounts:
        - name: conf-userinfo
          mountPath: /repo
        - name: secret-passwordinfo
          mountPath: /repo

  volumes:
    - name: conf-userinfo
      configMap:
        name: configmap-info
    - name: secret-passwordinfo
      secret:
        secretName: secret-info
      
    
