---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-server-1
spec:
  minReadySeconds: 2
  replicas: 4
  selector:
    matchLabels:
      app: dev-env
  template:
    metadata:
      labels:
        app: dev-env
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - jenkins
                      - docker
      containers:
        - name: nginx
          image: nginx