---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-server
spec:
  minReadySeconds: 2
  replicas: 4
  selector:
    matchLabels:
      app: dev-env
  template:
    metadata:
      labels:
        app: dev-env
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: rank
                    operator: Gt
                    values:
                      - "10"
      containers:
        - name: nginx
          image: nginx