apiVersion: v1
kind: Pod
metadata:
  name: always
  labels:
    env: qa
spec:
  restartPolicy: Always
  containers:
    - name: redis
      image: redis:7.2
      ports:
        - containerPort: 6379
  
