---
apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    env: uat
spec:
  restartPolicy: Never
  containers:
    - name: redis
      image: redis:7.2
      args:
        - sleep
        - 10s