---
apiVersion: v1
kind: Pod
metadata:
  name: onfailure
  labels:
    env: uat
spec:
  restartPolicy: OnFailure
  containers:
    - name: redis
      image: redis:7.2
      args:
        - sleep
        - 10M

---

apiVersion: v1
kind: Pod
metadata:
  name: onfailure
  labels:
    env: uat
spec:
  restartPolicy: OnFailure
  containers:
    - name: redis
      image: redis:7.2
      args:
        - sleep
        - 10s
