---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-app
  namespace: dev
  labels:
    role: frontend
    env: pre-prod
spec:
  minReadySeconds: 1
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      containers:
        - name: vote-app
          image: 
          imagePullPolicy: Always
          env:
            - name: 
              value: 
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /
            initialDelaySeconds: 2
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 8080
              path: /
            initialDelaySeconds: 5
            successThreshold: 1