apiVersion: v1
kind: Pod
metadata:
  name: pod-label-1
  labels:
    env: dev
spec:
  containers:
    - name: httpd
      image: httpd
      ports:
        - containerPort: 80
          protocol: TCP

---

apiVersion: v1
kind: Pod
metadata:
  name: pod-label-2
  labels:
    env: qa
spec: 
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
          protocol: TCP

---

apiVersion: v1
kind: Pod
metadata:
  name: pod-label-3
  labels:
    env: uat
spec:
  containers:
    - name: redis
      image: redis
      ports:
        - containerPort: 6379
          protocol: TCP