---
# Source: reusable/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-env
  labels:
    app: prod-env
    env: prod    
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prod-env
      env: prod
  template:
    metadata:
      labels:
          app: prod-env
          env: prod
    spec:
      containers:
      - name: poojastore
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 300m
            memory: 300Mi
          requests:
            cpu: 250m
            memory: 250Mi
