---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: jenkins
  labels:
    env: dev  
spec:
  schedule: '*/5 * * * *'
  jobTemplate:
    metadata:
      labels:
        env: dev
    spec:
      template:
        metadata:
          labels:
            app: test
        spec:
          restartPolicy: OnFailure
          containers:
            - name: jenkins
              image: Jenkins/Jenkins
              ports:
                - containerPort: 8080