---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: k8s-replicaset
spec:
  minReadySeconds: 1
  replicas: 1
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - azure
          - aws
          - gcp
      - key: network
        operator: NotIn
        values:
          - vpc
          - subnet
          - routetable
      - key: devops
        operator: In
        values:
          - ansible
          - git
          - jenkins
      - key: databases
        operator: NotIn
        values:
          - mysql
          - nosql
          - mangodb
  template:
    metadata:
      labels:
        app: gcp
        network: natgateway
        devops: git
        databases: oracledb
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - name: nginx-webport
              protocol: TCP
              containerPort: 80
        - name: nop
          image: batchusivaji/nopcommerce:latest
          ports:
            - name: nop-webport
              protocol: TCP
              containerPort: 5000


---
apiVersion: v1
kind: Service
metadata:
  name: k8s-service
spec:
  type: LoadBalancer
  selector:
    app: gcp
    network: natgateway
    devops: git
    databases: oracledb 
  ports:
    - name: nginx
      port: 80
      protocol: TCP
      targetPort: nginx-webport
      nodePort: 30006
    - name: nop
      port: 5000
      protocol: TCP
      targetPort: nop-webport
      nodePort: 30007