apiVersion: apps/v1
kind: Deployment
metadata:
  name: nop-deployment
  namespace: dev
  labels:
    app: nop
spec:
  minReadySeconds: 4
  replicas: 1
  selector:
    matchLabels:
      app: nop
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name: nop
      labels:
        app: nop
    spec:
      containers:
        - name: nopcommerce
          image: batchusivaji/nopcommerce:latest
          ports:
            - containerPort: 5000