---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  minReadySeconds: 1
  replicas: 3
  selector:
    matchLabels:
      app: dev
  template:
    metadata:
      labels:
        app: dev
    spec:
      containers:
        - name: nginx
          imagePullPolicy: Always
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: pvc-claim
              mountPath: /usr/share/nginx/html
      volumes:
        - name: pvc-claim
          persistentVolumeClaim:
            claimName: pvc-data
