---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-vol
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  storageClassName: premium-rwo
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /dev/tmp
  