---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nop-db-k8s
  labels:
    name: nop-db-k8s-app
spec:
  minReadySeconds: 2
  replicas: 3
  selector:
    matchLabels:
      app: nop-db-k8s-app
  template:
    metadata:
      labels:
        app: nop-db-k8s-app 
    spec:
      containers:
        - name: nop-db-k8s
          image: batchusivaji/nopcommerce:latest
          ports:
            - containerPort: 5000
          env: # Setting Enviornmental Variables
            - name: DB_HOST  # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: db-user-name
                  key: host
            - name: DB_NAME  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: db-user-name
                  key: host
            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom:
                 secretKeyRef:
                  name: db-credetials  # Secret Name
                  key: username
            -  name: DB_PASSWORD # Setting Database password from Secret
               valueFrom:
                 secretKeyRef:
                   name: db-credetials
                   key: password


     


---
apiVersion: v1
kind: Service
metadata:
  name: nop-db-k8s-svc
  labels:
    app: nop-db-k8s-app-k8s
spec:
  type: LoadBalancer
  selector:
    app: nop-db-k8s-app-k8s
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
      nodePort: 32000
