---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-manifest
  labels:
    env: qa
    purpose: deploy
spec:
  minReadySeconds: 2
  replicas: 1
  selector:
    matchExpressions:
      - key: dev
        operator: In
        values:
          - app
          - webapp
      - key: uat
        operator: NotIn
        values: 
          - cloud
          - devops
  template: # Pod template
    metadata:
      name: nginx
      labels:
        dev: app
        uat: webapp
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80

---
apiVersion: v1 
kind: Service
metadata:
  name: service-lb
spec:
  type: LoadBalancer
  selector:
    dev: app  # Matches the label selector in the Deployment
    uat: webapp
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 8080