---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs
  labels:
    env: qa
spec:
  minReadySeconds: 3
  replicas: 3
  selector:
    matchLabels:
      app: pre-pod
  template:
    metadata:
      labels:
        app: pre-pod
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
              protocol: TCP
        - name: jenkins
          image: shaikkhajaibrahim/deploy-sample:v1.0
          ports:
           - containerPort: 8080
             protocol: TCP
  
---
apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  type: NodePort
  selector:
    app: pre-pod
  ports:
    - name: nginx
      port: 80
      targetPort: 80
      protocol: TCP
    - name: jenkins
      port: 8080
      targetPort: 8080
      protocol: TCP

