---
apiVersion: v1
kind: Service
metadata:
  name: nop-service
  labels:
    app: dev
  selector:
    app: nop
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 32000
  type: LoadBalancer