---
apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  name: new-pvc-claim # Sets name of PV
  labels:
    app: postgres
spec:
  storageClassName: premium-rwo
  accessModes:
    - ReadWriteOnce # Sets read and write access
  resources:
    requests:
      storage: 10Gi # Sets volume size