---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset-1
spec:
  minReadySeconds: 1
  selector:
    matchLabels:
      app: dev-env
  template:
    metadata:
      labels:
        app: dev-env
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins
          ports:
            - containerPort: 8080

