---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset
spec:
  minReadySeconds: 1
  selector:
    matchLables:
      app: dev-env
  template:
    metadata:
      lables:
        app: dev-env
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxsurge: 25%
      maxunavailable: 25% 
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins
          ports:
            - containerPort: 8080
