---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-server
spec:
  minReadySeconds: 2
  replicas: 1
  selector:
    matchLabels:
      app: dev-env
  template:
    metadata:
      labels:
        app: dev-env
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - dev-env
                  
      containers:
        - name: nginx
          image: nginx