---
apiVersion: v1
kind: Pod
metadata:
  name: restartalways
  labels:
    app: alpine-app
    env: dev-environment
spec:
  restartPolicy: Always
  containers:
    - name: alpine
      image: alpine
      args:
        - sleep
        - 10s