---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
data:
  username: admin
  password: adminadmin
  mongodb.conf: |
    storage:
      dbpath: /data/db
    replication:
      replSetName: "rs0"
      
    
