---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
data:
  username: admin
  password: password
  mongodb.conf: |
    storage:
      dbpath: /data/configdb
    replication:
      replSetName: "rs0"
    
