---
apiVersion: v1
kind: Service
metadata:
  name: nop-svc
spec:
  type: LoadBalancer
  selector:
    prod: nginx
    web: demo
  ports:
    - name: svc-nop
      protocol: TCP
      port: 5000
      targetPort: nopcommerce
      nodePort: 31000
