app:
  name: prod-env
  data:
    app: prod-env
    env: prod
  replicascount: 2
  image: nginx:latest
  computerc:
    requests:
      cpu: 250m
      memory: 250Mi
    limits:
      cpu: 300m
      memory: 300Mi
hpa:
  enabled: false
  maxreplicas: 10
  minreplicas: 2
