---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod-1
spec:
  volumes:
    - name: my-volume
      hostPath:
        path: /dev/devops
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /devops
          name: my-volume