---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    dev: pre-prod
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchExpressions:
      - key: qat
        operator: In
        values:
          - jenkins
          - nginx
      - key: uat
        operator: NotIn
        values:
          - dev
          - pre-prod
          - prod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      annotations: 
        imageregistry: https://hub.docker.com/
      labels:
        qat: nginx
        uat: demo
    spec:
      containers:
        - name: nopcommerce-port
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: my-database 
            - name: POSTGRES_USER
              value: posgres-db
            - name: POSTGRES_PASSWORD
              value: learningthought
          volumeMounts:
            - name: pvc-volume
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "250Mi"
              cpu: "250m"
            limits:
              memory: "800Mi"
              cpu: "1"
      restartPolicy: Always
      volumes:
        - name: pvc-volume 
          persistentVolumeClaim:
            claimName: pvcclaim
