---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvcclaim
spec:
  resources:
    requests:
      storage: 2Gi
    limits:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard