---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nop
  labels:
    dev: nop
spec:
  minReadySeconds: 5
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchExpressions:
      - key: prod
        operator: In
        values:
          - jenkins
          - nginx
      - key: web
        operator: NotIn
        values:
          - dev
          - pre-prod
          - prod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      annotations:
        imageregistry: https://hub.docker.com/
      labels:
        prod: nginx
        web: demo
    spec:
      containers:
        - name: web-nopcommerce
          image: batchusivaji/devops:v1.0
          ports:
            - name: nopcommerce
              containerPort: 5000
              protocol: TCP
          resources:
            requests:
              cpu: "0.5"
            limits:
              cpu: "5"
              
          startupProbe:
            failureThreshold: 2
            periodSeconds: 7
            successThreshold: 1
            httpGet:
              path: /
              port: nopcommerce
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 2
            successThreshold: 1
            httpGet:
              path: /
              port: nopcommerce
          readinessProbe:
            failureThreshold: 4
            periodSeconds: 1
            successThreshold: 2
            httpGet:
              path: /
              port: nopcommerce

