---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-manifest
  labels:
    env: qa
    purpose: deploy
spec:
  minReadySeconds: 2
  replicas: 1
  selector:
    matchLabels:
      dev: app  
  template: # Pod template
    metadata:
      name: nginx
      labels:
        dev: app
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
  