---
apiVersion: v1
kind: Namespace
metadata:
  name: uat

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
  annotations:
    kubernetes.io/change-cause: "image updated to v3.0"
  namespace: uat
spec:
  minReadySeconds: 2
  replicas: 1
  selector:
    matchLabels:
      dev: deploy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template: # Pod template
    metadata:
      labels:
        dev: deploy
    spec:
      containers:
        - name: webserver
          image: batchusivaji/devops:v3.0
          ports:
            - name: nodeserverport
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 3
            successThreshold: 1 
          readinessProbe:
            httpGet: 
              path: /
              port: 80
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 1
            




