---
apiVersion: v1 
kind: Service
metadata:
  name: service
  namespace: uat
spec:
  type: LoadBalancer
  selector:
    dev: deploy  # Matches the label selector in the Deployment
  ports:
    - name: port
      port: 80
      targetPort: nodeserverport