---
apiVersion: v1
kind: Pod
metadata:
  name: deploy
spec:
  containers:
    - name: nginx
      imagePullPolicy: Always
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: pvc-claim
          mountPath: /usr/share/nginx/html
  volumes:
    - name: pvc-claim
      persistentVolumeClaim:
        claimName: pvc